### ISSUE TITLE
Mapping fields of contacts

### ISSUE THREAD

**Issue by samuelmafra** [dadolun95/magento2-brevo-sendinblue#2]
Hello,

The synchronization of contacts works, but we do not have the fields such as First Name, Last Name, Phone...

Would it be possible to map these fields?

Thank you.

**Comment by dadolun95** [comment]
Hi @samuelmafra,

The module doesn't map firstname, lastname and other customer fields for contacts that make only the subscription from the default newsletter frontend form.
It sync these data only if the subscibed email contacts make also a registration on magento (it's not necessary to do the registration before the subscription, the module collects these data on Brevo also for newer registrations matching the email). 
Same sync will happen for customer registrations with newsletter subscription checkbox activated. 

Let me know if this scenario works also on your Magento instance. If you still have sync problems please write me your Magento2 version so I can check myself, make fixes if necessary and come back to you.

**Comment by samuelmafra** [comment]
Hello @dadolun95,

I've always used MailChimp to sync contacts, and it mapped the name to other fields. In campaigns we can use these fields as "Hello %Name%".

Understand that the module does not map these fields, that's fine...

Another problem is that we have multiple stores, with different domains. We did tests configuring the API in the Global scope. In the scopes of each store, we selected the individual list that we have from Brevo.

However, only one list is syncing, as too many do not sync.

Should the module correctly sync each store with its respective subscribers?

Magento 2.4.5-p3 php 7.4

**Comment by dadolun95** [comment]
Hello @samuelmafra 

I've tested the module in different scopes on the first stable version, was about 1 year ago and it works. 
But many updates happened from then.
I'll check this scenario with Magento 2.4.5-p3 and PHP 7.4 and then return to you with an answer.

**Comment by dadolun95** [comment]
Hello @samuelmafra 

I've updated the module cause sync contacts seems broken getting configured list ID for storeview scope after implementation of magento2 message queue system.
Now "contact sync" button write adminhtml current storeview id on message queue as parameter.
With the new 1.0.13 version you can use "contact sync" button from default and store view scopes.
Contacts on brevo keeps the list configured for each storeview based on newsletter subscriber assigned store id.
Keep in mind that if you have "Need to Confirm" Magento2 configuration set as "Yes" (found on this path "Stores > Configuration > Customers > Newsletter") contacts not confirmed will be inserted into auto generated "Temp - DOUBLE OPTIN" list on Brevo.
Let me know if 1.0.13 module version works for you as worked on my local environment (Magento 2.4.5-p3 | PHP 7.4)

Remember to star the repository if you are comfortable with it.

**Comment by samuelmafra** [comment]
Hello @dadolun95 ,

Sorry for delay.

After the update or synchronization it worked for different stores.

Mapping name, surname and other fields does not seem to work, even with the customer registration.
